### ISSUE TITLE
Allow to configure secrets required as `defaultCertificate` of ingresses

### ISSUE THREAD

**Issue by corvus-ch** [appuio/component-openshift4-ingress#16]
## Context

The property `defaultCertificate` of an ingress takes the name of a Secret containing the certificate can key to be used by default. As of now, the component does not allow to manage those secretes. The component should allow to configure those secrets. It should also support to use `cert-manager` to create those secrets.

```yaml
  openshift4_ingress:
    ingressControllers:
      default:
        defaultCertificate:
          name: ingress-default-cert
      example.com:
        defaultCertificate:
          name: ingress-example-com-cert

    secrets:
      ingress-example-com-cert:
        stringData:
          tls.crt: ?{vaultkv:${cluster:tenant}/${cluster:name}/whildcard-example-com/cert}
          tls.key: ?{vaultkv:${cluster:tenant}/${cluster:name}/whildcard-example-com/key}

    cert_manager_certs:
      ingress-default-cert:
        … # Spec of cert-manager.io/v1/Certificate
```

Reuse keys in `cert_manager_certs` as values for `spec.secretName` of the created `Certificate` resource by default, but allow users to override that field from the hierarchy, if they really want.

## Alternatives

🤷🏼
